CREATE TABLE IF NOT EXISTS  WEATHER (
  COUNTRY VARCHAR (32),
  CITY VARCHAR (32),
  P_TEMP_F DOUBLE,
  P_TEMP_C DOUBLE,
  L_TEMP_F DOUBLE,
  L_TEMP_C DOUBLE,
  P_OBS_TIME DATETIME,
  L_OBS_TIME DATETIME
);